/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as MainImport } from "./routes/main";
import { Route as GameImport } from "./routes/game";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const MainRoute = MainImport.update({
  id: "/main",
  path: "/main",
  getParentRoute: () => rootRoute,
} as any);

const GameRoute = GameImport.update({
  id: "/game",
  path: "/game",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/game": {
      id: "/game";
      path: "/game";
      fullPath: "/game";
      preLoaderRoute: typeof GameImport;
      parentRoute: typeof rootRoute;
    };
    "/main": {
      id: "/main";
      path: "/main";
      fullPath: "/main";
      preLoaderRoute: typeof MainImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/game": typeof GameRoute;
  "/main": typeof MainRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/game": typeof GameRoute;
  "/main": typeof MainRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/game": typeof GameRoute;
  "/main": typeof MainRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/game" | "/main";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/game" | "/main";
  id: "__root__" | "/" | "/game" | "/main";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GameRoute: typeof GameRoute;
  MainRoute: typeof MainRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  MainRoute: MainRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game",
        "/main"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
