name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            # Create apps directory if it doesn't exist
            mkdir -p ~/apps

            # Check if the repository is already cloned
            if [ ! -d "~/apps/jigsaw/.git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/${{ github.repository }}.git ~/apps/jigsaw
            fi

            # Navigate to the project directory
            cd ~/apps/jigsaw

            # Pull latest changes
            git pull

            # Install dependencies and build
            pnpm install --frozen-lockfile
            pnpm build

            # Start or restart the application
            pm2 restart jigsaw || pm2 start "pnpm start" --name jigsaw
